config/routes.rb
Rails.application.routes.draw do
  resources :appointments, only: [:index, :create, :update]
  root :to => 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  def get_data
    {
        "title": title,
        "id": id,
        "start": formatted_date(start_at),
        "end": formatted_date(end_at)
    }
  end

  def formatted_date(date)
    date.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :availabilities

  # TODO: Think about storing this with it pre-parsed
  # To successfully work with String '.in_time_zone'
  def parse_time_zone
    time_zone.gsub(/\(GMT.*?\)\s/, '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.where('start_at >= ? and end_at <= ?', parsed_date(params[:start]), parsed_date(params[:end]))
    data = @appointments.map(&:get_data)
    render :json => data, :status => :ok
  end

  def create
    @appointment = Appointment.new(appointment_params)
    @appointment.save
    redirect_to root_path
  end

  def update
    @appointment = Appointment.find(params[:id])
    params.delete(:id)
    @appointment.attributes = appointment_params
    @appointment.save
    render nothing: true
  end

  def appointment_params
    params.permit(:title, :start_at, :end_at)
  end

  def parsed_date(date)
    Date.parse(date)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def get_route(student_id)
    if student_id
      coaches_path
    else
      student_new_path
    end
  end
end

app/views/home/index.html.erb
<div id="calendar"></div>
<div class="modal fade" id="eventModal" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal" type="button">x</button>
        <h4 class="modal-title">Create Appointment</h4>
      </div>
      <div class="modal-body">
        <%= form_tag appointments_path, method: 'post', class: 'form-horizontal' do %>
            <div class="form-group">
              <%= label_tag :title, "Title", class: 'control-label col-sm-2' %>
              <div class="col-sm-10">
                <%= text_field_tag :title, '',class: 'form-control' %>
                <%= hidden_field_tag :start_at %>
                <%= hidden_field_tag :end_at %>
              </div>
            </div>
            <div class="form-group">
              <%= label_tag :when, "When:", class: 'control-label col-sm-2' %>
              <div class="col-sm-10" id="when" style="margin-top:5px;"></div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <%= submit_tag 'Save' %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SlotBooking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>